In [1]:
# importing  pandas library
import pandas as pd
import numpy as np

In [2]:
obj = pd.Series(np.array(np.arange(1,10,2)))
obj

0    1
1    3
2    5
3    7
4    9
dtype: int32

In [3]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [4]:
obj.values

array([1, 3, 5, 7, 9])

In [5]:
obj2 = pd.Series([13,4,5],index=['d','a','e'])
obj2

d    13
a     4
e     5
dtype: int64

In [6]:
obj2.index

Index(['d', 'a', 'e'], dtype='object')

In [7]:
obj2.values

array([13,  4,  5], dtype=int64)

In [8]:
obj2['d']

13

In [9]:
obj2['a'] = 6

In [10]:
obj2

d    13
a     6
e     5
dtype: int64

In [11]:
obj2[obj2 > 2]

d    13
a     6
e     5
dtype: int64

In [12]:
obj2[obj2 > 2].sum()

24

In [13]:
max(obj2[obj2>2])

13

In [14]:
'a' in obj2

True

In [15]:
4 in obj2


False

In [16]:
sdata = {'ohio': 3500,'texas':5687,'oregon':4834,'utah':5799}
sdata

{'ohio': 3500, 'texas': 5687, 'oregon': 4834, 'utah': 5799}

In [17]:
pd.Series(sdata)

ohio      3500
texas     5687
oregon    4834
utah      5799
dtype: int64

In [18]:
states = ['california','ohio',"oregon",'utah']
obj4 = pd.Series(sdata,index=states)
obj4

california       NaN
ohio          3500.0
oregon        4834.0
utah          5799.0
dtype: float64

In [19]:
obj4[obj4 > 200].mean()

4711.0

In [20]:
pd.isnull(obj4)

california     True
ohio          False
oregon        False
utah          False
dtype: bool

In [21]:
pd.notnull(obj4)

california    False
ohio           True
oregon         True
utah           True
dtype: bool

In [22]:
pd.notna(obj4)

california    False
ohio           True
oregon         True
utah           True
dtype: bool

In [23]:
obj3 = pd.Series(sdata)
obj3

ohio      3500
texas     5687
oregon    4834
utah      5799
dtype: int64

In [24]:
obj4

california       NaN
ohio          3500.0
oregon        4834.0
utah          5799.0
dtype: float64

In [25]:
obj3+obj4

california        NaN
ohio           7000.0
oregon         9668.0
texas             NaN
utah          11598.0
dtype: float64

In [26]:
obj4.name = 'population'

In [27]:
obj4

california       NaN
ohio          3500.0
oregon        4834.0
utah          5799.0
Name: population, dtype: float64

In [28]:
obj4.index.name = 'state'
obj4

state
california       NaN
ohio          3500.0
oregon        4834.0
utah          5799.0
Name: population, dtype: float64

In [29]:
pd.DataFrame(obj4)

population
state                 
california         NaN
ohio            3500.0
oregon          4834.0
utah            5799.0

### DataFrame

In [30]:
data = {'state':['ohia','ohia','ohia','nevada','nevada','nevada'],
         'year':[2000,2001,2003,34004,34324,3534],
          'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

        

In [31]:
frame = pd.DataFrame(data)

In [32]:
frame.name = 'information'

In [33]:
frame

state   year  pop
0    ohia   2000  1.5
1    ohia   2001  1.7
2    ohia   2003  3.6
3  nevada  34004  2.4
4  nevada  34324  2.9
5  nevada   3534  3.2

In [34]:
frame.index.name = 'serial number'
frame

state   year  pop
serial number                    
0                ohia   2000  1.5
1                ohia   2001  1.7
2                ohia   2003  3.6
3              nevada  34004  2.4
4              nevada  34324  2.9
5              nevada   3534  3.2

In [35]:
frame.head(2)

state  year  pop
serial number                 
0              ohia  2000  1.5
1              ohia  2001  1.7

In [36]:
frame2 = pd.DataFrame(data,columns = ['year','state','pop','debt'],
                    index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one     2000    ohia  1.5  NaN
two     2001    ohia  1.7  NaN
three   2003    ohia  3.6  NaN
four   34004  nevada  2.4  NaN
five   34324  nevada  2.9  NaN
six     3534  nevada  3.2  NaN

In [37]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [38]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [39]:
# Change the order of columns with respec to it's values
frameUpadate = pd.DataFrame(data,columns=['year','state','pop'])

In [40]:
frameUpadate.index.name = 'serial number'

In [41]:
frameUpadate

year   state  pop
serial number                    
0               2000    ohia  1.5
1               2001    ohia  1.7
2               2003    ohia  3.6
3              34004  nevada  2.4
4              34324  nevada  2.9
5               3534  nevada  3.2

In [42]:
frameUpadate[frameUpadate['year'] > 2001]

year   state  pop
serial number                    
2               2003    ohia  3.6
3              34004  nevada  2.4
4              34324  nevada  2.9
5               3534  nevada  3.2

In [43]:
frameUpadate = frameUpadate.reindex(['two','three','four','five','one','zero'])

In [44]:
frameUpadate

year state  pop
serial number                 
two             NaN   NaN  NaN
three           NaN   NaN  NaN
four            NaN   NaN  NaN
five            NaN   NaN  NaN
one             NaN   NaN  NaN
zero            NaN   NaN  NaN

In [45]:
frameUpadate.index = (['two','three','four','five','one','zero'])

In [46]:
frameUpadate.index.name = 'Serial Number'

In [47]:
frameUpadate

year state  pop
Serial Number                 
two             NaN   NaN  NaN
three           NaN   NaN  NaN
four            NaN   NaN  NaN
five            NaN   NaN  NaN
one             NaN   NaN  NaN
zero            NaN   NaN  NaN

### Slicing


In [48]:
frame2['state']

one        ohia
two        ohia
three      ohia
four     nevada
five     nevada
six      nevada
Name: state, dtype: object

In [49]:
frame2.state

one        ohia
two        ohia
three      ohia
four     nevada
five     nevada
six      nevada
Name: state, dtype: object

In [50]:
pd.DataFrame(frame2.loc[:,'state'])

state
one      ohia
two      ohia
three    ohia
four   nevada
five   nevada
six    nevada

In [51]:
# Columns can be added and modified 
frame2["debt"] = np.arange(6)

In [52]:
frame2

year   state  pop  debt
one     2000    ohia  1.5     0
two     2001    ohia  1.7     1
three   2003    ohia  3.6     2
four   34004  nevada  2.4     3
five   34324  nevada  2.9     4
six     3534  nevada  3.2     5

In [53]:
val = pd.Series([1,3,4],index= ['two','four','five'])

In [54]:
val

two     1
four    3
five    4
dtype: int64

In [55]:
frame2['debt'] = val

In [56]:
frame2

year   state  pop  debt
one     2000    ohia  1.5   NaN
two     2001    ohia  1.7   1.0
three   2003    ohia  3.6   NaN
four   34004  nevada  2.4   3.0
five   34324  nevada  2.9   4.0
six     3534  nevada  3.2   NaN

In [57]:
del frame2['debt']

In [58]:
frame2

year   state  pop
one     2000    ohia  1.5
two     2001    ohia  1.7
three   2003    ohia  3.6
four   34004  nevada  2.4
five   34324  nevada  2.9
six     3534  nevada  3.2

## Nested Dictionary

In [61]:
pop = {'nevada':{2001:2.4,2002:3.5},
        'ohio':{200:1.5,202:2,205:5}}

In [62]:
pop

{'nevada': {2001: 2.4, 2002: 3.5}, 'ohio': {200: 1.5, 202: 2, 205: 5}}

In [63]:
fram3 = pd.DataFrame(pop)

In [64]:
fram3

nevada  ohio
2001     2.4   NaN
2002     3.5   NaN
200      NaN   1.5
202      NaN   2.0
205      NaN   5.0

In [68]:
pdata = {'ohia':fram3['ohio'][:-1],
        'nevada':fram3['nevada'][:2]}

In [70]:
pd.DataFrame(pdata)

ohia  nevada
200    1.5     NaN
202    2.0     NaN
2001   NaN     2.4
2002   NaN     3.5

In [71]:
fram3.index.name = 'year'; 
fram3.columns.name = 'state'
fram3

state  nevada  ohio
year               
2001      2.4   NaN
2002      3.5   NaN
200       NaN   1.5
202       NaN   2.0
205       NaN   5.0

In [75]:
arr = fram3.values
arr

array([[2.4, nan],
       [3.5, nan],
       [nan, 1.5],
       [nan, 2. ],
       [nan, 5. ]])

In [77]:
np.ndim(arr)

2

### Index Objects

In [79]:
obj = pd.Series(range(4),index= list('abcd'))

In [80]:
obj

a    0
b    1
c    2
d    3
dtype: int64

In [88]:
obj = pd.DataFrame(obj)

In [89]:
obj.index.name = 'index'
obj.columns.name = 'numbers'

In [90]:
pd.DataFrame(obj)

numbers  0
index     
a        0
b        1
c        2
d        3

In [91]:
obj.index is 'a'

False

In [92]:
obj.index is 'index'

False

In [96]:
fram3.index

Int64Index([2001, 2002, 200, 202, 205], dtype='int64', name='year')

In [97]:
fram3

state  nevada  ohio
year               
2001      2.4   NaN
2002      3.5   NaN
200       NaN   1.5
202       NaN   2.0
205       NaN   5.0

In [98]:
fram3.columns

Index(['nevada', 'ohio'], dtype='object', name='state')

In [99]:
'ohio' in fram3.columns

True